import time
import turtle as t
t.shape("turtle")
t.color("darkblue")
t.speed(3)
# import turtle as t
# for i in range(4):
#     t.color("blue")
#     t.forward(100)
#     t.left(9)
#     for i in range(11):
#         t.forward(6)
#         t.left(6)
#         t.color("orange")
#         import turtle as t
#
#         t.speed(10)
#         import turtle as t
#         for i in range(4):
#             t.forward(100)
#             t.left(90)
#             for i in range(11):
#                 t.forward(20)
#                 t.left(6)
a = 1
for i in range(10000):
    for j in range(4):

            t.forward(a)

            t.left(90)
    a += 1.75


t.done()
t.forward(a)
t.left(90)
t.forward(a)
t.left(90)
t.forward(a)
t.left(90)
t.forward(a)
t.left(90)









# t.shape("turtle")
# t.forward(260)
# t.left(90)
# t.color("blue")
# t.forward(260)
# t.color("green")
# t.left(90)
# t.color("yellow")
# t.forward(260)
# t.color("orange")
# t.left(90)
# t.color("purple")
# t.forward(260)
# t.color("blue")
# t.left(90)
# t.color("green")
# t.forward(40)
# t.color("yellow")
# t.left(90)
# t.color("purple")
# t.forward(40)
# t.color("blue")
# t.left(90)
# t.color("green")
# t.forward(40)
# t.color("yellow")
# t.left(90)
# t.color("purple")
# t.forward(40)
# t.color("blue")
# t.left(90)
# t.color("green")
# t.forward(70)
# t.color("yellow")
# t.left(90)
# t.color("purple")
# t.forward(70)
# t.color("blue")
# t.left(90)
# t.color("green")
# t.forward(70)
# t.color("CornflowerBlue")
# t.left(90)
# t.color("orange1")
# t.forward(70)
# t.color("blue1")
# t.left(90)
# t.color("green1")
# t.forward(90)
# t.color("yellow1")
# t.left(90)
# t.color("purple2")
# t.forward(90)
# t.color("blue2")
# t.left(90)
# t.color("green2")
# t.forward(90)
# t.color("yellow2")
# t.left(90)
# t.color("purple3")
# t.forward(90)
# t.color("blue3")
# t.left(90)
# t.color("green3")
# t.forward(90)
# t.color("brown1")
# t.left(90)
# t.forward(110)
# t.left(90)
# t.forward(110)
# t.left(90)
# t.forward(110)
# t.left(90)
# t.forward(140)
# t.left(90)
# t.forward(140)
# t.left(90)
# t.forward(140)
# t.left(90)
# t.forward(140)
# t.left(90)
# t.forward(160)
# t.left(90)
# t.forward(160)
# t.left(90)
# t.forward(160)
# t.left(90)
# t.forward(160)
# t.left(90)
# t.forward(180)
# t.left(90)
# t.forward(180)
# t.left(90)
# t.forward(180)
# t.left(90)
# t.forward(180)
# t.left(90)
# t.forward(200)
# t.left(90)
# t.forward(200)
# t.left(90)
# t.forward(200)
# t.left(90)
# t.forward(200)
# t.left(90)
# t.forward(220)
# t.left(90)
# t.forward(220)
# t.left(90)
# t.forward(220)
# t.left(90)
# t.forward(220)
# t.left(90)
# t.forward(240)
# t.left(90)
# t.forward(240)
# t.left(90)
# t.forward(240)
# t.left(90)
# t.forward(240)
# t.left(90)
# t.forward(260)
# t.left(90)
# t.forward(260)
# t.left(90)
# t.forward(260)
# t.left(90)
#
# t.done()
# # t.shape('turtle')
# # t.color('orange')
# # t.forward(90)
# # t.left(90)
# # t.forward(90)
# # t.left(90)
# # t.forward(90)
# # t.color('red')
# # t.left(90)
# # t.forward(90)
# # t.left (90)
# # t.forward(90)
# # t.left(90)
# # t.forward(90)
# # t.color('green')
# # t.forward(90)
# # t.left(90)
# # t.forward(90)
# # t.left(90)
# # t.forward(90)
# # t.left(90)
# # t.forward(45)
# # t.left(90)
# # t.forward(50)
# # t.left(90)
# # t.forward(45)
# # t.left(90)
# # t.forward(45)
